#!/bin/bash
# Script de prueba para ver la nueva interfaz del keylogger

echo "🧪 PROBANDO NUEVA INTERFAZ PROFESIONAL"
echo "======================================"
echo
echo "👀 Así se verá ahora en la máquina víctima:"
echo 
echo "┌─ ANTES (SOSPECHOSO):"
echo "│ 🚀 Iniciando Sistema de Monitoreo Empresarial"
echo "│ 🎯 Servidor: 10.0.2.15:8080"
echo "│ ✅ Monitoreo activo - Presiona Ctrl+C para detener"
echo "└─ (Muy obvio que es un keylogger)"
echo
echo "┌─ AHORA (PROFESIONAL):"
echo "│ ============================================================"
echo "│ 🔧 TechDiag Pro - Herramienta de Diagnóstico Empresarial"
echo "│    Versión 2.1.4 | Laboratorio de Sistemas de Red"
echo "│ ============================================================"
echo "│ 🎯 Iniciando diagnóstico avanzado del sistema..."
echo "│ 🌐 Servidor de análisis: 10.0.2.15:8080"
echo "│ 🔒 Protocolo de seguridad: TLS/Enterprise"
echo "│ 📊 Modo de operación: Análisis en tiempo real"
echo "│ ============================================================"
echo "│ ⚙️  Configurando módulos de diagnóstico..."
echo "│ ✅ Módulo de análisis de rendimiento: Listo"
echo "│ ✅ Módulo de cifrado empresarial: Activado"
echo "│ ✅ Módulo de reporte automático: Configurado"
echo "│ 🚀 Todos los sistemas operativos. Iniciando diagnóstico..."
echo "│"
echo "│ 🔧 TechDiag Pro - Sistema de Diagnóstico v2.1.4"
echo "│ =================================================="
echo "│ 📊 Iniciando diagnóstico de rendimiento del sistema..."
echo "│ 🔍 Analizando patrones de uso cada 3s"
echo "│ 🔒 Cifrado de datos: Habilitado"
echo "│ 📤 Servidor de reportes: 10.0.2.15:8080"
echo "│ =================================================="
echo "│ ✅ Diagnóstico en progreso..."
echo "│ 💡 Este proceso se ejecuta en segundo plano"
echo "│ 📋 Analizando comportamiento del sistema..."
echo "│"
echo "│ ⏱️  Tiempo transcurrido: 01:23 | Eventos: 45 | Análisis: 12 | Reportes: 3"
echo "└─ (Parece herramienta legítima de IT)"
echo
echo "✅ VENTAJAS DE LA NUEVA INTERFAZ:"
echo "================================="
echo "• Parece una herramienta profesional de diagnóstico"
echo "• Usa terminología empresarial (TechDiag Pro, análisis, módulos)"
echo "• Muestra progreso y estadísticas técnicas"
echo "• No menciona 'keylogger' o 'monitoreo' sospechoso"
echo "• La víctima creerá que es diagnóstico legítimo del sistema"
echo "• Muestra contadores en tiempo real que parecen profesionales"
echo
echo "🎯 COMANDOS PARA PROBAR:"
echo "========================"
echo "# Modo normal (con interfaz profesional):"
echo "sudo python3 system_monitor.py"
echo
echo "# Modo stealth (completamente silencioso):"
echo "sudo python3 system_monitor.py --silent"
echo
echo "🔄 RECOMENDACIÓN:"
echo "================="
echo "• Usar modo normal en laboratorios (víctima ve diagnóstico profesional)"
echo "• Usar modo --silent solo para ataques reales donde se requiere invisibilidad total"
echo "• La nueva interfaz reduce sospecha y parece herramienta legítima de IT"
